### ISSUE TITLE
Guide completion

### ISSUE THREAD

**Issue by Ivan768** [pl-luk/linuxbook#1]
I have the same Yoga C13 chromebook. I followed the guide apart from disabling the WP with Suzy-Q cable. It seems to me that the guide is not complete (e.g. Verified Boot) so I was wondering if there remains more to be added to it. 
So far I was able to install and boot standalone Linux from Tianocore but had no luck implementing dual boot because the Chrome OS partitions were not visible to Ubuntu/Debian installer.
I appreciate your work on linuxbook, thanks!

**Comment by pl-luk** [comment]
Hi,
yes you are right the guide is incomplete and currently not really useful (I currently have not much time to spare on this project). I have a semi-working setup on my Yoga C13 which should be able to dual-boot Linux and Chrome OS (although I can neither confirm nor deny it as I haven't put any effort in that direction). The final goal of this project is to leave all the Chromebook boot stuff in place and only cryptographically resign it. However the cryptographic part is not checking out at the moment and I can only boot Linux in dev mode (but with the native bootloader). With a little bit of tweaking you might be able to get a dual boot working using my current setup. However, doing so is a completely different approach than you are taking with Tianocore. In fact, you would have to ditch Tianocore and restart.... If you want to do so I can send you my semi-working thing to get standalone Linux up and running and how I think you might be able achieve a dual boot.

**Comment by Ivan768** [comment]
These machines require a lot of effort. I will give it another shot, and if I fail I might take you up on the offer. Thanks for the fast response.

**Comment by pl-luk** [comment]
Guide is now usable: 66a3485bed5877475038ebe657575ffae01edbed
